/*
 * TApp.java
 *
 * Created on April 3, 2007, 2:35 PM
 */

package cotex;

/**
 *
 * @author  Ming
 */
public class TApp extends javax.swing.JFrame {
    
    /** Creates new form TApp */
    public TApp() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        mTabs = new javax.swing.JTabbedPane();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        getContentPane().add(mTabs);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        mNode.getModel().execute( new TExitCmd() );
    }//GEN-LAST:event_formWindowClosing

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane mTabs;
    // End of variables declaration//GEN-END:variables
    
    private TNode mNode;
    
    public void run() {
        
        this.setTitle("Cotex");
        this.setResizable(true);
        this.setSize(800, 600);
        
        mNode = TNodeFactory.createInstance("working");
        
        mTabs.addTab("Working", mNode.getView().getGuiRoot() );
        
        this.setVisible(true);
        
    }
}
