/*
 * TWorkingNodeView.java
 *
 * Created on April 3, 2007, 2:46 PM
 */

package cotex.working;

import cotex.*;

/**
 *
 * @author  Ming
 */
public class TWorkingNodeView extends javax.swing.JPanel implements INodeView {
    
    /** Creates new form TWorkingNodeView */
    public TWorkingNodeView() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        mCmdPanel = new javax.swing.JPanel();
        mBtnLock = new javax.swing.JButton();
        mBtnCommit = new javax.swing.JButton();
        mTextAreaScrollPane = new javax.swing.JScrollPane();
        mTextArea = new javax.swing.JTextArea();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        mCmdPanel.setLayout(new javax.swing.BoxLayout(mCmdPanel, javax.swing.BoxLayout.X_AXIS));

        mCmdPanel.setMinimumSize(new java.awt.Dimension(100, 24));
        mCmdPanel.setPreferredSize(new java.awt.Dimension(400, 24));
        mBtnLock.setText("Lock");
        mCmdPanel.add(mBtnLock);

        mBtnCommit.setText("Commit");
        mCmdPanel.add(mBtnCommit);

        add(mCmdPanel);

        mTextArea.setColumns(20);
        mTextArea.setRows(5);
        mTextAreaScrollPane.setViewportView(mTextArea);

        add(mTextAreaScrollPane);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mBtnCommit;
    private javax.swing.JButton mBtnLock;
    private javax.swing.JPanel mCmdPanel;
    private javax.swing.JTextArea mTextArea;
    private javax.swing.JScrollPane mTextAreaScrollPane;
    // End of variables declaration//GEN-END:variables
    
    
    public javax.swing.JPanel getGuiRoot() {
        return this;
    }
}
